export const TOKU_NAME = 'Sanso'
export const DARK_HOLE = 369810644
export const TOKU_CHAT = -1001311183194
// export const TOKU_CHAT = -1001845823201
export const TOKU_CHANNEL = -1001446681491
export const EGOID = 1016239817
export const VIKA_ID = 503220461
export const FIREWORKY_ID = 5711731837
export const LELOUCH_ID = -1002063312382
export const BOT_ID = 5627801063
const TOKUID = 332320628
export const ADMINS = [TOKU_CHANNEL, DARK_HOLE, EGOID, TOKUID, FIREWORKY_ID, VIKA_ID]
export const ANGELINA_LIST: number[] = [554683512] // 6256371434
export const SHOCK_PATALOCK = 'CQACAgIAAx0EbgUG4QACARhkQSVHnxcut0o6kWQPtWKq2lsTXwACfywAAr81uUlinNRcNS2fFC8E'
export const WORLD_TRIGGER = 'CAACAgEAAx0CbgUG4QACAS5kQTVsPpYJb3nUAAHDaO9_YTfgvNYAAtAAA3u8bAw_gR9puBpcHy8E'
export const NOT_TOMORROW = 'BAACAgIAAxkBAAIS_mTagYxp1cu4YSR72xOujVkbFEnJAAJNMQACouPYSrs03uFp0sRSMAQ'
export const TOMORROW = 'BAACAgIAAxkBAAITKmTnobPVIEuPBgABsRcNQxxJ8exGJwAC4zcAArLsIEthuXHGy-ba3zAE'
export const TOMORROW_HAPPY = 'BAACAgIAAxkBAAIaDWUgYY3PlTPSzR8uG91XuuWkvPnWAAK9QgACLeEAAUlnlPqpA00UHzAE'
export const PATPAT = 'CgACAgQAAxkBAAIaEWUgYoyC6YNTzDjcF5uwB6zWiehTAAJZBAAC4uRcUHa-q_KmzqdfMAQ'
export const NADEKO_CALLING = 'CgACAgQAAxkBAAITDGTd2M4YohWB0TqKWgMmzFBmQmsnAALCAgAC7_EMU3DLeeVhu66JMAQ'
export const KILLING_STICKER = 'CAACAgIAAxkBAAITJ2TglJLxFvqiVuVaPuJPaoHfNol4AAL7KQACUc3ZSJgMUrSarBhNMAQ'
export const MONOKUMA = 'CgACAgQAAxkBAAITRGTt-QG3sH1S1MMv6AbM-9XKwJ0KAAL-AgAC-JAMU356feNlYd9iMAQ'
export const COUNTER = 'CgACAgIAAxkBAAITRWTt-RErQAnrQ6JXbQb0QSr1purCAAJjMAACeJNhSzII8-lcNY5uMAQ'
export const RUBY_MEOW = ['AwACAgQAAxkBAAITU2T7Vx2TwYUYKOH4S4TbJGercP50AAJvGQAC1q_hUzWoJXjkkRauMAQ', 'AwACAgIAAxkBAAIYJ2UIe4yl27MHRcsfX1nxE2QikKZ5AAKqNwACF_1JSNlDEmUq-v8jMAQ']
export const EIGHTY_SIX = 'AgACAgIAAxkBAAITVmT7V3cpWlfb7WG5QXLcnLqtTFb-AALhzTEbLQrgS7AyWsUWeT_MAQADAgADeAADMAQ'
export const DRAGONBALL = 'BAACAgIAAxkBAAITa2T8RZsaG5lNUS8xHK8ndtSjJ5V5AAKJNgAC8wzZS6AKG8Jx0_Q2MAQ'
export const HELP = 'CAACAgUAAxkBAAICNmUa80bXpRINymeCsnYJoxXwbvznAAJlCAACgqn5VUpWgc3_JzhpMAQ'
export const TEA_STICKERS = ['AgADihgAAu4FAUg', 'AgAD0BEAAtLWCUg', 'AgADoRcAArefAUg']
export const COFFEE_STICKERS = ['AgAD7ikAAvdHoUk', 'AgADSyEAAtp_SEo', 'AgADURYAAos5KUk']
export const ALCO_STICKERS = ['AgADtxoAAqDgEUs', 'AgADFBgAAmsrgUg', 'AgADrBgAAj0SSUk', 'AgADfQwAAiFgWVU', 'AgADlyMAAn28YEs']
export const TEA_EMOJIS = ['🍵']
export const COFFEE_EMOJIS = ['☕️']
export const ALCO_EMOJIS = ['🥃', '🍻', '🍺', '🍷', '🍾']
export const KUGA_YUMA = [
    'AgACAgIAAx0CbgUG4QACAuNljxx1KftaJnn3lTIUWBKtIaibZAACUdMxG-56eUhofgABM2Ma0zYBAAMCAAN5AAM0BA',
    'AgACAgIAAx0CbgUG4QACAuRljxx1ikHHi3-dVbvzgajJOWgYugACUtMxG-56eUj__lBD7Re9iQEAAwIAA3kAAzQE',
    'AgACAgIAAx0CbgUG4QACAuVljxx1rEb0sc2_VlQduVQNX1kTPwACU9MxG-56eUjoSN3eccdb8wEAAwIAA3kAAzQE',
    'AgACAgIAAx0CbgUG4QACAuZljxx1xN_Ckm9h5SKMgTmVOKswyAACVdMxG-56eUhvCNTgJbmWngEAAwIAA3kAAzQE',
    'AgACAgIAAx0CbgUG4QACAudljxx1AbGUwzStcS5aXWg4n6InhAACVtMxG-56eUjXfyMZKbd4oQEAAwIAA3kAAzQE'
]
// Пон
export const PON_STICKER = 'CAACAgIAAxkBAAEhnnNkblkm-YkHGOAR1ltwGrPGDhGvMgACmygAAqCNOUshhm_UzqyrcC8E'
